---
abstract: 'A Catalyst View for Graphics::Primitive'
author:
  - 'Cory Watson, C<< <gphat@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-View-Graphics-Primitive
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Catalyst::Runtime: 5.7014
  Graphics::Primitive: 0.29
  Moose: 0.57
  Scalar::Util: 1.19
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
